definitions/region/common.yaml

Add R5, R9 and R10 regions

---

definitions/region/native_regions/IMACLIM_2.0.yaml
mappings/IMACLIM_2.0.yaml

@FlorianLeblancDr, please review.

Register IMACLIM 2.0

---

definitions/variable/emissions/emissions.yaml

- close https://github.com/IAMconsortium/common-definitions/issues/42

Update emissions.yaml, add description of Industrial Processes

---

definitions/variable/energy/secondary-energy-electricity.yaml
definitions/variable/energy/secondary-energy-non-electricity.yaml

Per a comment by @strefler in https://github.com/IAMconsortium/common-definitions/issues/34#issuecomment-1806065218, this PR changes the description of secondary-energy variables to clarify that biomass includes biogas

Clarify meaning of biomass in secondary-energy variables

---

definitions/variable/emissions/emissions.yaml
definitions/variable/energy/tag_all_sectors.yaml
definitions/variable/energy/tag_industrial_processes.yaml
definitions/variable/energy/tag_non_energy_sectors.yaml

This PR implements some suggestions by the @IAMconsortium/common-definitions-emissions group related to emissions from industrial processes.

Add details to emissions variables related to industrial processes

---

definitions/variable/emissions/tag_level-1-species.yaml

Add reporting category for CFC emissions

Add CFC to emissions reporting

---

definitions/variable/emissions/carbon-removal.yaml
definitions/variable/emissions/tag_carbon-management.yaml
definitions/variable/emissions/tag_carbon-removal.yaml

Add variables for carbon-removal technologies as requested (with some slight streamlining and simplifications).

Add gross-carbon-removal variables

---

definitions/variable/emissions/emissions.yaml
definitions/variable/emissions/tag_level-3-species.yaml

Based on bilateral conversion with @volker-krey and email exchange with Steve Smith

Add emissions variable for CEDS harmonization

---

definitions/variable/energy/final-energy.yaml

- fixes https://github.com/IAMconsortium/common-definitions/issues/132

fix occurence of tag in description different from use in variable

---

definitions/region/native_regions/IMAGE_v3.4.yaml

Added country definitions for IMAGE model regions based on: https://models.pbl.nl/image/Region_classification_map

Added country definitions for IMAGE regions

---

definitions/variable/agriculture/forestry.yaml

Forestry demand and production added to "agriculture" folder.
"agriculture" could be renamed to "AFOLU" for better fit.

added forestry demand and production

---

definitions/variable/land/land-cover.yaml
definitions/variable/sdg-indicators/sdg.yaml

move natural forest from sdg to land-cover to avoid duplicate entries in the full template

move natural forest from sdg to land-cover

---

definitions/variable/land/water-ecosystems.yaml

This PR adds water ecosystems.
I don't understand the following categories from the previous template, which I therefore excluded:
Water Ecosystems|Glaciers
Water Ecosystems|Mountains

added water ecosystems

---

mappings/AIM_Hub_Global.yaml
mappings/region_mappings_witch_6_0.yml

Migrating from ssp-workflow repository

Add WITCH 6.0 and AIM/HUB-Global 2.4 region mappings

---

definitions/variable/macro-economy/investment.yaml
definitions/variable/macro-economy/macroeconomic_other.yaml
definitions/variable/macro-economy/tag_energy-trade-type.yaml
definitions/variable/macro-economy/trade.yaml

Based on an email by @gunnar-pik, I added a further set of macro variables.

Add variables for capital stock, investment and trade

---

definitions/variable/emissions/carbon-management.yaml

This is a quick follow-up PR to #83 to clean up formatting, line-length and capitalization of one variable
fyi @jayfuhrman @strefler

Format and clean-up of carbon-capture variables

---

definitions/variable/afolu/agriculture.yaml
definitions/variable/afolu/food.yaml
definitions/variable/afolu/forestry.yaml
definitions/variable/afolu/land-cover.yaml
definitions/variable/afolu/water-ecosystems.yaml
definitions/variable/afolu/yield.yaml
definitions/variable/emissions/emissions.yaml
definitions/variable/energy/final-energy.yaml
definitions/variable/energy/resource.yaml
definitions/variable/energy/secondary-energy-electricity.yaml
definitions/variable/energy/secondary-energy-non-electricity.yaml
definitions/variable/macro-economy/consumption.yaml
definitions/variable/macro-economy/gdp.yaml
definitions/variable/macro-economy/investment.yaml
definitions/variable/macro-economy/labor-force.yaml
definitions/variable/population/population.yaml
definitions/variable/population/tag_age.yaml
definitions/variable/population/tag_education.yaml
definitions/variable/population/tag_gender.yaml
definitions/variable/sdg-indicators/sdg.yaml

This PR harmonizes naming conventions and ordering of attributes.

Clean up of attributes

---

definitions/variable/buildings/service.yaml

includes floor space for residential, commercial and combined buildings sector based on NAVIGATE legacy template

Adding minimal set of energy service indicators for buildings sector

---

definitions/variable/emissions/carbon-management.yaml
definitions/variable/emissions/tag_carbon-utilization.yaml
definitions/variable/energy/final-energy.yaml

Based on an email with suggested variables by @strefler.

Add variables for carbon-utilization to produce synfuels

---

definitions/variable/emissions/emissions.yaml

This PR adds variables that were "manually" added to the ScenarioMIP reporting template, see https://github.com/iiasa/ssp-submission-workflow/blob/main/definitions/variable/variables.yaml.

Add ScenarioMIP-CMIP7 emissions variables

---

definitions/variable/techno-economic/electricity-generation.yaml
definitions/variable/techno-economic/other-energy-transformation-technologies.yaml

This PR carries over the list of techno-economic variables from #99 by @rongqizhu, which was also requested by @gunnar-pik separately by email.
The proposed variable for variable vs. fixed operation and maintenance cost is not implemented here, this will be discussed in a follow-up issue and PR.

Add variables for capital cost, efficiency and technical lifetime

---

definitions/variable/energy/tag_all_sectors.yaml
definitions/variable/energy/tag_non_energy_sectors.yaml

Fixing this inconsistency found by @OFR-IIASA & @macflo8

Harmonize to "High-Value" notation or consistency

---

.github/workflows/pytest.yml
.github/workflows/validation.yml
definitions/variable/industry/production.yaml
definitions/variable/sdg-indicators/sdg.yaml

@OFR-IIASA identified this inconsistency in the units.

Harmonize units notation

---

definitions/variable/energy/tag_all_sectors.yaml

@macflo8 noticed that the energy and emissions sub-categories didn't align with ISIC and the "Production|..." variables. This PR harmonizes these variables.

Harmonize energy/emissions in industry with ISIC

---

definitions/variable/sdg-indicators/sdg.yaml

Adjust poverty lines to $2017 PPP to be in line with World Bank poverty lines
https://data.worldbank.org/indicator/SI.POV.DDAY
https://data.worldbank.org/indicator/SI.POV.LMIC
https://data.worldbank.org/indicator/SI.POV.UMIC

Update poverty lines to PPP2017

---

definitions/variable/energy/energy-prices.yaml

This PR adds final-energy prices by fuel (not including the sector). per discussion with @volker-krey and @OFR-IIASA.

Add final-energy prices by fuel (not sector)

---

mappings/AIM_3.0.yaml
mappings/AIM_Hub_Global.yaml

As requested by Shinichiro Fujimori

Fix AIM "Rest of Europe" R10 region mapping

---

definitions/variable/environment/biodiversity.yaml

More details on definitions and units

More details for biodiversity indicators

---

definitions/variable/emissions/carbon-management.yaml

This PR adds variables for CCS by source as requested by @strefler.

Add CCS variables by carbon source

---

definitions/variable/emissions/emissions.yaml
definitions/variable/energy/tag_all_sectors.yaml

Reimplementing the core of #228.
Closes #227 
FYI @IAMconsortium/common-definitions-emissions

Add sub-categories for emissions in transportation

---

definitions/variable/energy/secondary-energy-electricity.yaml
definitions/variable/energy/tag_secondary_electricity_sources.yaml
definitions/variable/techno-economic/electricity-generation.yaml

This PR adds tiers for electricity-related variables: installed capacity at tier 1, capacity-additions at tier 2, with a tier-bump of 1 for the sub-divisions of PV
FYI @IAMconsortium/common-definitions-energy

Add tiers for electricity-related variables

---

definitions/variable/energy/resource.yaml

This PR adds tiers for resource-extraction variables at tier 1.
FYI @IAMconsortium/common-definitions-energy

Add tier for resource-extraction variables

---

definitions/variable/afolu/agriculture.yaml

Clarification of definition:
Only harvested residues should be reported.

update definiton agricultural residues

---

definitions/variable/macro-economy/macroeconomic_other.yaml
definitions/variable/macro-economy/price.yaml

Same as defined and discussed in #38

Price carbon

---

definitions/region/native_regions/COFFEE_1.6.yaml
mappings/COFFEE_1.6.yaml

Added COFFEE 1.6 definition files.

Updating COFFEE version

---

definitions/region/native_regions/POLES/POLES_2.4.yaml

Add countries for POLES 2.4 native region definition

---

mappings/GCAM/GCAM_6.0.yaml
mappings/GCAM/GCAM_7.1.yaml

This is an alternative structure to #335 - I think it's easier to grasp what's happening.

Fix GCAM region mapping with nomenclature 0.26

---

README.md

To reduce confusion with modeling teams thinking that they have to report all variables...

Add note about scope of variable list

---

definitions/region/g20.yaml
definitions/region/regional-organizations.yaml
definitions/region/supranational-bodies.yaml

FYI @phackstock @dc-almeida - this will make importing region-hierarchies and mappings easier when also using all countries.

Define EU and AU as own hierarchy

---

definitions/variable/afolu/food-system.yaml

This PR adds mapping for legacy variables "Food Demand" and subcategories per email discussion with @flohump and @tmkhsgw.

Add legacy mapping for `Food Demand` variables
