IAMconsortium/common-definitions

definitions/region/native_regions/REMIND_3.1.yml
This PR fixes a half-baked attribute-renaming in #4 and fixes the ISO3 code in the definitions.
> The Netherlands Antilles was divided into Bonaire, Saint Eustatius and Saba (BQ, BES,
535), Curaçao (CW, CUW, 531) and Sint Maarten (Dutch part) (SX, SXM, 534).
https://www.iso.org/obp/ui/#iso:code:3166:AN
=> Remove `ANT` from region-definitions and add `BES`, `CUW`, `SXM` instead
FYI @renato-rodrigues
=> Update REMIND 3.1 region definitions to iso3-codes-attribute

definitions/region/common.yaml
This PR re-implements the region-clean-up (#13), ensuring consistency across R5, R9 and R10 country mappings.
The following design choices were made:
- The Baltic States are part of Europe/EU
- The R9 regions *India* and *China* should include only those countries
- The R10 Region *India+* and *China+* should include neighboring countries that are similar, i.e., on the Indian sub-continent or fit the description "Centrally-planned Asia" (and are close to China)
Of course, these mappings are only a guidance, because actual model implementations will only be an imperfect approximation to these mappings.
=> Harmonize country mappings

definitions/variable/emissions/emissions.yaml
This PR adds the variables for gross CO2 emissions (only counting the positive emissions, not any CO2 removal in a sector) developed in the NAVIGATE project.
This variable is the complement to the variables "Carbon Capture" with fossil fuels (to be added in a subsequent PR).
For discussion: do we add the variable tree related to carbon capture and gross-emissions from NAVIGATE directly, or are there any changes that should be made as a clean-up or for consistency?
=> Add variables for gross CO2 emissions

definitions/region/common.yaml
Updated the R10 regions to be consistent with the IPCC AR6 WGII Annex II R10 regions (https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Annex-II.pdf). 
There are some small nations which were already in the common-definitions R20 regions but were not included in any of the IPCC R10 regions (e.g. Taiwan, Hong Kong), which I left in. 
Also updated spelling of Czechia at R10 level.
Added Albania to Europe R10 (already in R5 and R9 levels)
=> Danhooke inconsistencies

definitions/variable/energy/secondary-energy-electricity.yaml, definitions/variable/energy/tag_non_biomass_renewables.yaml
This PR introduces the variable tree for `Secondary Energy|Electricity` based on the ENGAGE and NAVIGATE projects.
A few observations:
- PV is separated into residential-rooftop and commercial-rooftop. Should we add a sub-category for utility-scale "Open Land"? And "Floating"?
- ENGAGE has a variable for electricity generation from ammonia, but NAVIGATE does not. Should we add it here?
- ENGAGE and NAVIGATE have variables for Curtailment, Storage, Storage Losses and Transmission Losses, but they seem inconsistent with the idea of an "electricity supply mix" of this category. How to proceed?
=> Add variables for electricity generation

definitions/region/common.yaml
Added small countries that were in IPCC WGIII Annex II (https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Annex-II.pdf) but were not in existing list.
These were Seychelles, Andorra, Liechtenstein, Monaco, San Marino, Antigua and Barbuda, Saint Kitts and Nevis, Saint Vincent and the Grenadines, Cook Islands, Kiribati, the Marshall Islands, Nauru, Niue, Palau, Tuvalu, 
Also added Kosovo to R10 Europe for aggregation purposes.
=> Small countries

definitions/variable/energy/final-energy.yaml, definitions/variable/energy/tag_all_sectors.yaml, definitions/variable/energy/tag_carbon_removal.yaml
This PR does the following:
- move the variables for energy use for carbon removal to own section
- switch the ordering of the hierarchy from "fuel - technology" to "technology - fuel" for consistency with other "Final Energy" variables
Open questions: are there other carbon-removal technologies that should be included for reporting of their energy use?
Any comments @IAMconsortium/common-definitions-coordination @gidden?
=> Move energy use of carbon-removal to own section

definitions/variable/energy/final-energy.yaml
This PR fixes a mistake in the reference to variable-names in the legacy-project attributes
=> Use tags in legacy-project attributes

definitions/variable/macro-economy/gdp.yaml
This PR adds GDP variables in response to #53 using the 2010-USD as unit - however, the latest SSP-release (see http://data.ece.iiasa.ac.at/ssp/) used 2017-USD as unit for GDP projections.
Any suggestions/preferences on which one to use?
@IAMconsortium/common-definitions-coordination @IAMconsortium/common-definitions-macro-economy
=> Add GDP variables

.github/workflows/legacy.yml, definitions/variable/energy/final-energy.yaml, requirements.txt, tests/test_legacy.py
This PR adds a test and GitHub Actions workflow to guard against mistakenly adding variables that were marked as being superseded by new variables.
The way that legacy variables are marked in the common-definitions repository is by having an attribute with the legacy project name, currently "navigate" and "engage".
```yaml
- Final Energy|Carbon Removal|{Carbon Removal Option}|Electricity:
description: Electricity use for carbon removal by {Carbon Removal Option}
unit: EJ/yr
notes: See `Secondary Energy|Electricity|...` for the power generation mix
navigate: Final Energy|Carbon Removal|Electricity|{Carbon Removal Option}
```
The test workflow checks that all such attributes are not duplicates of variables in the VariableCodeList.
=> Guard against adding deprecated legacy variables

definitions/variable/emissions/emissions.yaml, definitions/variable/energy/final-energy.yaml, definitions/variable/energy/tag_all_sectors.yaml
This PR responds to a comment by @strefler in #36. It (proposes to) change the meaning of the Bunkers sector include all international aviation and shipping to avoid an inconsistency between oil and green fuels in international transportation.
=> Change "Bunkers" sector to mean international aviation and shipping

definitions/variable/emissions/emissions.yaml, definitions/variable/emissions/tag_level-1-species.yaml, definitions/variable/emissions/tag_level-2-species.yaml, definitions/variable/emissions/tag_level-3-species.yaml
Because there was some confusion about the use of the term "tier" in the emissions-species tag-lists, this PR refactors the emissions-species tag lists and adds comments
FYI @lolow @FlorianLeblancDr @orichters
=> Refactoring emissions-species detail categorization to `level`

README.md, definitions/variable/sdg-indicators/sdg.yaml, definitions/variable/sdg-indicators/tag_food.yaml, definitions/variable/sdg-indicators/tag_nitrogen-sources.yaml, definitions/variable/sdg-indicators/tag_recycled-materials.yaml
This PR copies the PR #53 and implements a number of clean-ups (given that @bs538 indicated he could not work on this over the next weeks).
See the list of commits for a clean step-by-step reporting of the changes that I implemented beyond the work done so far, trying to implement a consistent variable-naming and use of units.
A few open questions:
- what are the right units for ocean saturation?
- would it make sense to spell out MSA and BII in the variable names for clarity and readability
- why are the nitrogen variables named "Cropland Budget", and how is that related to nitrogen?
- what is V-DEM? (in the description of the indicator "Equality Before Law and Individual Liberty"
Related issues: #72 #62 
FYI @IAMconsortium/common-definitions-sdg-indicators
=> Add SDG indicators from the SHAPE project

definitions/variable/sdg-indicators/sdg.yaml, tests/test_legacy.py, tests/test_reserved_terms.py
In #55, we agreed to use square brackets to identify methods or operations, e.g. `... [Share]` instead of the previously used subcategories like `...|Share`.
This PR adds a test to guard against adding subcategory-methods-variables in the future and renames one variable from the SDG domain.
fyi @IAMconsortium/common-definitions-sdg-indicators
=> Guard against methods-terms as sub-categories

definitions/variable/emissions/emissions.yaml
This PR adds the list of components for several emissions-variables (where the value is *not* just the sum of sub-components because of the "Energy and Industrial Processes" auxiliary-reporting category.
This list of components is not yet correctly resolved  by **nomenclature** (tags are not replaced and checked against the codelist if they are in a list), but it could still be useful to have this information here as an example for future use.
fyi @IAMconsortium/common-definitions-emissions
=> Add explicit list of components of emissions

definitions/variable/energy/resource.yaml
This variable was just requested in another project, and I guess it will be relevant in other projects, too.
=> Add variable for fossil resource extraction

definitions/variable/energy/secondary-energy-non-electricity.yaml
This PR adds categories for production of liquid fuels from hydrogen where hydrogen is modeled explicitly as a (traded) intermediate commodity. This is a proposed compromise for @fschreyer and @pkyle, see #84 
Given the difference on how e-fuels are represented across models, allowing both and letting the modelers (or the project leads where this template is used) make the choice.
closes #84
=> Add secondary-energy variables for liquids from hydrogen

definitions/variable/emissions/emissions.yaml, definitions/variable/energy/final-energy.yaml, definitions/variable/energy/tag_secondary_energy_carriers_with_sources.yaml
This PR adds final-energy and emissions variables where the source of a secondary energy carrier is explicitly stated.
For clarification - before this PR, only the following variable existed in the common-definitions variable list
> Final Energy|Liquids
This PR will add
> Final Energy|Liquids|Biomass
> Final Energy|Liquids|Oil
> Final Energy|Liquids|Coal
> Final Energy|Liquids|Gas
also for emissions and sectoral disaggregation variables, and also for Solids and Gases.
This PR responds to requests by @robertpietzcker and @orichters in #39 and @OFR-IIASA (offline).
=> Add source-categories for secondary energy carriers

definitions/variable/emissions/emissions.yaml, definitions/variable/emissions/tag_level-1-species.yaml, definitions/variable/emissions/tag_level-2-species.yaml, definitions/variable/emissions/tag_level-3-species.yaml
In NAVIGATE and ENGAGE, the descriptions of the CO2-emissions variables explicitly referred to "fossil CO2" only. This was dropped (my mistake, I guess?) when transferring the variables to the common-definitions repo.
Please advise whether to add "fossil" to all CO2 emissions variable definitions.
=> Rework CO2 emissions to only refer to fossil CO2

definitions/region/native_regions/IMAGE_v3.4.yaml, mappings/IMAGE_v3.4.yaml
This PR adds the region definitions for IMAGE 3.4, copy-pasting and making minor adjustments from earlier versions (3.2 in ENGAGE and 3.3 in GEO7 and NAVIGATE) - please double-check.
Two additional requests:
1. In the common-definitions repo, we added all G20 members as possible comparison-regions (see [here](https://github.com/IAMconsortium/common-definitions/blob/main/definitions/region/g20.yaml), please check if any IMAGE regions can be mapped directly to G20 members. I have remove the EU-mapping because this seems to be quite different from actual EU membership (UK, NO) to avoid confusion later on...
2. Please add countries to the region-definitions, see for example from the [AIM 3.0 definitions](https://github.com/IAMconsortium/common-definitions/blob/main/definitions/region/native_re …
=> Add region definitions and mappings for IMAGE  3.4

definitions/variable/agriculture/agriculture.yaml
This PR is for discussion of adding variables for agricultural production and consumption.
I'm wondering whether to copy over the duplications from the ENGAGE variable template, in particular:
```
Agricultural Demand|Crops
Agricultural Demand|Crops|...
Agricultural Demand|Energy
Agricultural Demand|Energy|Crops
Agricultural Demand|Energy|Crops|1st generation
Agricultural Demand|Energy|Crops|2nd generation
Agricultural Demand|Energy|Residues
Agricultural Demand|Livestock
Agricultural Demand|Livestock|...
Agricultural Demand|Non-Energy
Agricultural Demand|Non-Energy|Crops
Agricultural Demand|Non-Energy|Crops|...
Agricultural Demand|Non-Energy|Livestock
Agricultural Demand|Non-Energy|Livestock|...
```
where `...` indicates distinction by Feed, Food and Other...
Comparing this to the AGMIP …
=> Variables for agricultural production and consumption

definitions/variable/agriculture/food.yaml, definitions/variable/sdg-indicators/sdg.yaml
This PR adds the variables for food demand based on the xlsx overview developed by @flohump @realxinzhao and @kanishkan91.
I added references to the agmip variables.
For consistency, I suggest that we also rename this variable by adding "[per capita]" at the end, to highlight that these are per-capita variables.
It's not clear to me whether we need to also add "Food Energy Supply" (which existed in ENGAGE and NAVIGATE), but which seem to be overlapping with sub-categories of Agricultural Production, right?
=> Add variables for food demand

definitions/region/native_regions/REMIND_3.1.yml, definitions/variable/land/land-cover.yaml, definitions/variable/land/land_cover.yaml, definitions/variable/sdg-indicators/sdg.yaml
This PR adds variables for land cover based on the xlsx overview developed by @flohump @realxinzhao and @kanishkan91.
This PR does NOT include subcategories for cropland and forests - this will be implemented in a follow-up PR once this discussion is finished and the iniatl set of land-cover variables are merged.
A few observations:
- I added the variable "Land Cover|Water Ecosystems", which has been missing from the templates in NAVIGATE and ENGAGE
- I assigned all water-ecosystems variables as tier 3
- Is there a particular reason why glaciers are a sub-category of water ecosystems?
- The variable for built-up area land cover was renamed for consistency with the naming convention, see [here](https://docs.ece.iiasa.ac.at/iamc/variable.html#variable-naming-conventions)
Please review the …
=> Add variables for land cover

definitions/region/native_regions/REMIND-MAgPIE_3.4-4.8.yml, mappings/REMIND-MAgPIE_3.4-4.8.yml
We would like to register the latest REMIND-MAgPIE version. After merging the PR, I would also need the corresponding permission to upload.
Thank you!
=> Adding REMIND-MAgPIE 3.4-4.8 according to current model version

.github/workflows/pytest.yml, .github/workflows/validation.yml, definitions/region/native_regions/IMAGE_v3.4.yaml, requirements.txt
Closes #141, closes #140.
This PR came about as I wanted to quickly finish iamconsortium/nomenclature-iamc#397 to get a new release on the road.
When running the tests, I noticed that it seems #129 is only compliant with the pypi version of nomenclature and not the latest GitHub version
=> Use pypi and latest nomenclature for CI

definitions/variable/energy/secondary-energy-non-electricity.yaml
This PR implements the variables for gases-production from hydrogen as suggested by @robertpietzcker in https://github.com/IAMconsortium/common-definitions/pull/106#issuecomment-2328867412.
The implementation follows the distinction into hydrocarbons from electricity (directly) vs. explicitly modelled hydrogen, which was introduced in #106.
=> Add variables for gases from hydrogen

definitions/variable/macro-economy/trade.yaml
Based on an email by @gunnar-pik, I realized that the goods-trade variable introduced in #57 deviated from the NAVIGATE and ENGAGE templates by separating imports and exports. I'm not sure if that distinction is strictly necessary?
Also, I suggest to add the Goods category to clarify that this should not include the energy or emissions-allowance trade (see #147).
=> Refactor the goods-trade variable

definitions/region/common.yaml
Per comments by @jkikstra and @byersiiasa, this PR adds an "International" region that can be used for data that cannot be assigned to a specific region, e.g., emissions related to bunker fuels in international aviation and shipping.
Using this region would allow that aggregation of "World = sum of regions + International" works as expected.
closes #74
=> Add an "International" region

definitions/variable/emissions/emissions.yaml, definitions/variable/emissions/tag_level-1-species.yaml, definitions/variable/emissions/tag_level-2-species.yaml, definitions/variable/emissions/tag_level-3-species.yaml
As discussed by email and stated by @volker-krey in https://github.com/IAMconsortium/common-definitions/pull/113#issuecomment-2396250910, this PR reverts the restriction of CO2-emissions to only refer to fossil sources (#113).
=> Revert change to fossil-CO2 in emissions variables

definitions/variable/macro-economy/investment.yaml
This PR adds investment variables suggested by @gunnar-pik related to uranium extraction and all relevant combinations of secondary-energy-carriers (with their source) and CCS.
=> Add all combinations of secondary-energy carriers to investment variables

definitions/variable/energy/secondary-energy-non-electricity.yaml
This PR adds variables for non-electricity secondary energy, including a distinction into with-CCS-vs.-without CCS, based on a spreadsheet sent by @gunnar-pik.
This implementation adds a few combinations that may not make sense - they will be filtered out in a follow-up PR (but this requires some work on the nomenclature package (see https://github.com/IAMconsortium/nomenclature/issues/416).
FYI @IAMconsortium/common-definitions-energy @IAMconsortium/common-definitions-coordination
=> Add capacity variables for non-electricity secondary energy

definitions/variable/water/water.yaml
This PR adds variables for non-energy water withdrawal and consumption. Water-related energy variables will be added after merging #106.
FYI @IAMconsortium/common-definitions-coordination @IAMconsortium/common-definitions-land - adding the land team because we do not have a water team...
=> Add variables for non-energy water withdrawal & consumption

definitions/region/common.yaml
Per a comment by @korsbakken, this PR changes the description of the "China+ (R10)" region to avoid the phrase "centrally planned", which doesn't apply to South Korea (which is part of that region for legacy reasons).
The new description as "Eastern Asia" follows the IPCC AR WG3 Annex 2, page 1823, see https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Annex-II.pdf
Closes #160
=> Change description of "China+ (R10)" region

definitions/variable/energy/secondary-energy-electricity.yaml, definitions/variable/energy/tag_secondary_electricity_sources.yaml
This PR adds investment variables suggested by @gunnar-pik for capacity and capacity additions of electricity generation.
One clarifying question: when I read this description, the capacity-addition variable should be reported as net-change (not just new investment). So if 1 GW of wind turbines are built and 0.2 GW of wind turbines are decommissioned in the same year (due to age), the variable should be reported as 0.8 GW.
Is my understanding correct, and should this be made more explicit in the description or notes?
=> Add capacity (addition) variables for electricity generation

definitions/variable/afolu/agriculture.yaml, definitions/variable/afolu/food-system.yaml, definitions/variable/afolu/forestry.yaml, definitions/variable/afolu/land-cover-change.yaml, definitions/variable/afolu/tag_crop-non-energy.yaml, definitions/variable/afolu/tag_forestry-raw-products.yaml, definitions/variable/afolu/tag_forestry-semi-finished.yaml, definitions/variable/afolu/water-ecosystems.yaml
After merging #180, I noticed one "wrong" variable name ("Energy crops" instead of all-capitalized words), and I couldn't help myself but also clean up the descriptions of the AFOLU variable names for consistency
=> Harmonize descriptions in the AFOLU domain

definitions/variable/energy/secondary-energy-electricity.yaml, definitions/variable/energy/secondary-energy-non-electricity.yaml
This PR adds investment variables suggested by @gunnar-pik for capacity and capacity additions of non-electricity energy-carriers. And fixing a typo introduced in #177.
FYI @IAMconsortium/common-definitions-energy
=> Add capacity-additions variables for non-electricity energy

definitions/variable/industry/production-prices.yaml
This PR implements the requested variables via email by @gunnar-pik for prices of industrial commodities - however, given that the related variables are called "Production|...", I propose to rename to "Price|Production|..." instead of "Price|Industry|...".
Please chime in until the end of this week if you have objections.
=> Add price variables for production commodities

definitions/region/g20.yaml, mappings/COFFEE_1.5.yaml
This PR fixes an error in the list of the G20-countries identified by @korsbakken in #203 and harmonizes the region-name with the `nomenclature.countries` convention.
=> Harmonize Russia in G20-list with `nomenclature.countries`

definitions/region/g20.yaml, definitions/variable/emissions/emissions.yaml, definitions/variable/macro-economy/investment.yaml
Implementing the variable list from [here [sheet: IAMC variables]](https://docs.google.com/spreadsheets/d/1HKfl21NX8wohPEHpHlmf5XithknPw8zjLpVe4MiOU9U/edit?usp=sharing)
General context documented under #151 (currently bit outdated).
Should address:
Minimum:
Optional / can leave for future versions:
=> Cmip7 Emissions Variables List (v0)

definitions/variable/industry/production-prices.yaml
This PR adds variables for industrial prices of non-metallic minerals and fixes an incorrect mapping to legacy variables.
=> Quickfix for production prices

definitions/variable/emissions/carbon-management.yaml, definitions/variable/emissions/tag_carbon-capture-source.yaml, definitions/variable/emissions/tag_geological-storage.yaml
This PR implements changes discussed by email among the emissions-group (see in particular the email by @strefler on October 10).
The changes in particular:
- add variables for carbon capture by source (fossil, biomass, synthetic, processes)
- add tiers and bounds for existing carbon-capture variables
- add the list of components of the top-level "Carbon Capture" variable to clarify that "Carbon Capture|Fossil" and "Carbon Capture|Geological Storage" should not be added up
[EDIT by @gidden]: The October 10 email includes the following attachment [MissingVariables-CDR-CCS.xlsx](https://github.com/user-attachments/files/17747560/MissingVariables-CDR-CCS.xlsx)
[EDIT by @gidden]:
We propose 3 main variable elements:
1. the "reservoir tree" denoting the provenance of carbon in each storage …
=> Add variables for carbon capture by source

definitions/variable/energy/final-energy.yaml, definitions/variable/energy/tag_all_sectors.yaml, definitions/variable/energy/tag_non_energy_sectors.yaml, definitions/variable/energy/tag_secondary_energy_carriers_level-2.yaml, definitions/variable/energy/tag_secondary_energy_carriers_level-3.yaml
Per a nudge by @gunnar-pik, this PR uses a new nomenclature-feature to assign different tiers from tag-lists.
The tier is defined in the variable - if a tag-list is used for that variable, the tag-item can increment the variable-tier using `^1` or `^2`. This way, final-energy variables at a "high" aggregate, e.g *Final Energy|Agriculture|Electricity* keep the tier-1 assignment, but "higher-resolution" variables like *Final Energy|Non-Energy Use|Non-Ferrous Metals|Liquids|Electricity* have a higher tier-value.
See the attached file for a simple view of the resulting tier-assignment.
[final-energy-with-tier.xlsx](https://github.com/user-attachments/files/17784067/final-energy-with-tier.xlsx)
closes #212
=> Implement proper tiers for final-energy variables

definitions/variable/emissions/carbon-removal.yaml, definitions/variable/emissions/emissions.yaml, definitions/variable/energy/secondary-energy-non-electricity.yaml, definitions/variable/macro-economy/investment.yaml
This PR adds tiers for emissions variables, and also fixes wrong tier-assignment for investment, secondary-energy, capacity (addition) and carbon-removal. Follow-up to #215.
fyi @IAMconsortium/common-definitions-emissions
=> Implement tiers for emissions variables

definitions/variable/techno-economic/electricity-generation.yaml, definitions/variable/techno-economic/other-energy-transformation-technologies.yaml
This PR adds variables for technology-specific parameters. The `*` is a wildcard so that any technology can be added to a variable, e.g. 
> Capital Cost|Electricity|Biomass|1
> Capital Cost|Electricity|Biomass|CCGT
can be used in reporting.
Requires https://github.com/IAMconsortium/nomenclature/issues/432 to validate the units as well as the variable names.
=> Add technology-specific variables for techno-economic parameters

definitions/variable/emissions/carbon-management.yaml
This PR implements more detailed variables for energy-supply carbon-capture variables per a list sent by @strefler.
There  are three important changes compared to earlier projects (NAVGATE and ENGAGE):
- Add additional variable "Carbon Capture|Energy" and subsectors to report how much capture happens in total in the energy system
- Rename "Carbon Capture|[Fossil/Biomass]" to "Carbon Capture|Energy|[Fossil/Biomass]" for clarity
- Reorder the variable-names to have fossil/biomass/synfuels at the end, similar to how energy-variables are structured
=> Add carbon-capture variables for energy supply

definitions/variable/emissions/carbon-management.yaml, definitions/variable/industry/tag_industry_sectors.yaml
This PR implements variables for carbon-capture in industry, distinguishing between energy consumption and industrial processes based on a list sent by @strefler.
Similar to #230, this PR restructures the variable tree to more closely aligned with emissions and energy variables. In the process, we are getting rid of confusing/overlappung variables like
- Carbon Capture|Fossil|Energy|Demand|Industry
- Carbon Capture|Industry|Fossil (which also seems to include industrial processes)
=> Add variable for carbon-capture in industry

definitions/variable/emissions/emissions.yaml
Updated definition of wetland emissions
=> definition of wetland emissions

definitions/variable/transport/energy-services.yaml, definitions/variable/transport/tag_drive-types.yaml
Per request by @gunnar-pik, this PR adds variables for energy service demand related to road transportation.
After a brief discussion with @vruijven, this PR replaces abbreviations with more descriptive terms to be more accessible to a wider audience. A mapping from NAVIGATE to the new form is included.
=> Add variables for road transportation service demand

definitions/variable/emissions/emissions.yaml
This PR adresses the issue raised by @jkikstra here:
https://github.com/IAMconsortium/common-definitions/pull/226#issuecomment-2527932422
Furthermore, this PR renames 
`Emissions|{Level-3 Species}|AFOLU|Land|Other Land Use and Land-Use Change`
to 
`Emissions|{Level-3 Species}|AFOLU|Land|Land Use and Land-Use Change`
because there is already `Emissions|{Level-3 Species}|AFOLU|Land|Other` which includes `Emissions and removals from land that cannot be accommodated in other categories `
=> Minor update AFOLU Emissions Land Use and Land-Use Change

definitions/variable/emissions/emissions.yaml
This is a quick follow-up from #236 to harmonize the formatting and use a more intuitive ordering.
Also, this PR removes the explicit components because they are in these cases just the (obvious) sum of the subcategories of the variables. In order to keep the yaml files concise, we should only use components if it deviates from the standard case.
@jkikstra @flohump
=> Change order of land-emissions and remove components

definitions/variable/emissions/emissions.yaml
This PR adds variables to distinguish between fugitive and combustion emissions at the energy-supply-by-fuel resolution, based on a discussion between @volker-krey and Steve Smith related to CEDS and CMIP6 harmonization.
Note that "Emissions|{Level-2 Species}|Energy|Supply|Combustion" and "Emissions|{Level-2 Species}|Energy|Supply|Fugitive" are already included in the template.
=> Add variables for combustion and fugitive emissions of fuel supply

definitions/variable/emissions/emissions.yaml
This PR adds two variables 
- Gross Removals|CO2
- Gross Removals|CO2|AFOLU
Together with `Gross Emissions|CO2` and `Gross Emissions|CO2|AFOLU` this allows to understand how net emissions emerge. 
This PR is linked to issues #224 and #222 
For AFOLU, we could add more subcategories.
=> added gross removals in emissions

definitions/variable/energy/energy-prices.yaml
This PR adds tiers for energy-price variable at tier 1 with tier-bump for sub-categories of energy carriers (see [this file](https://github.com/IAMconsortium/common-definitions/blob/main/definitions/variable/energy/tag_secondary_energy_carriers_level-2.yaml))
FYI @IAMconsortium/common-definitions-energy
=> Add tiers for price variables

definitions/variable/energy/tag_all_sectors.yaml
This PR adds `Final Energy|Industry|Non-Ferrous Metals|Copper*` variables.
=> Add copper tag in energy sector tag list

definitions/variable/emissions/tag_carbon-management.yaml
FYI @strefler @jayfuhrman @danielhuppmann 
Are we ok with just one FE CCS variable? There is a bit of overlap with DAC here. I would say energy for purely the capture of DAC go into the DAC variable, but transportation and storage energy (if modeled) go into CCS.
=> add CCS to cmanagement definitions

mappings/IMAGE_v3.4.yaml
While working on something else, noticed this misnamed region. It raised an error in my script but I assume it doesn't in workflow repos because there is no check whether the native constituent regions belong to the same model where they are listed.
=> Fix India G20 mapping for IMAGE 3.4

definitions/variable/afolu/tag_livestock.yaml
Dairy is only milk and cheese but not eggs.
This PR fixes this issue by adding an extra category for eggs.
=> Fix livestock products definition for dairy <-> eggs

definitions/region/common.yaml
Add two countries that in 2010, like Aruba in 1986, separated from the Netherlands to become a constituent country inside the Kingdom of the Netherlands
For more, see https://en.wikipedia.org/wiki/Kingdom_of_the_Netherlands 
This is a small PR, but points to larger questions (which could be transferred into a new Issue, i think): 
(a) when to add new countries to the mapping?
(b) is there a way to ensure that there is no overlap?
(c) is there a way to ensure completeness?
(d) should we force IAM mappings to be up-to-date with the latest common R5/R9/R10 mapping?
**How to review?**
=> Add Curacao and Sint Maarten

definitions/variable/energy/tag_all_sectors.yaml, definitions/variable/industry/production-prices.yaml, definitions/variable/industry/production.yaml, definitions/variable/industry/tag_chemical_commodities.yaml, definitions/variable/industry/tag_iron_commodities.yaml, definitions/variable/industry/tag_non-ferrous_commodities.yaml, definitions/variable/industry/tag_non_metallic_commodities.yaml, definitions/variable/industry/tag_paper_commodities.yaml
This PR adapts the industrial-sector production and price variable to use the new tier-implementation, so that all tiers are kept as integer in the DataStructureDefinition and not as strings.
FYI @IAMconsortium/common-definitions-industry 
Also closes #258 reported by @klau506
=> Fix tiers of industry-production and price variables

definitions/variable/afolu/tag_forestry-semi-finished.yaml, definitions/variable/sdg-indicators/sdg.yaml
Standardize the notation for `t DM` units to ensure consistency, as both `tDM` and `t DM` were previously used.
=> Units: add consistency in t DM units

definitions/region/native_regions/MESSAGEix-GLOBIOM-GAINS_2.1-R12.yaml, mappings/MESSAGEix-GLOBIOM-GAINS_2.1-M-R12.yaml
This PR adds a new model-region-group "MESSAGEix-GLOBIOM-GAINS 2.1-R12" and the mapping for the "M"-variant of that model.
=> Add region definition and mapping for "MESSAGEix-GLOBIOM-GAINS 2.1-R12"

definitions/variable/macro-economy/gdp.yaml, definitions/variable/macro-economy/macroeconomic_other.yaml
I went through the national scenario template to see what needed to be imported (double check welcomed).
[https://data.ene.iiasa.ac.at/ar6-scenario-submission/static/files/national.zip](https://data.ene.iiasa.ac.at/ar6-scenario-submission/static/files/national.zip)
- Mostly Debt variables
- I found Investment|Clean Energy not well defined, which seems to be a sub-category of Investment|Energy Supply so I leave it behind
- Public Consumption is redundant with Expenditure|Government, which is a better name, so I leave it behind
- Labour Supply is defined under "Labor Force" now
- remaining: Subsidies, Taxes, Trade variables which should come in a dedicated PR
=> Varaible From National scenario template

definitions/variable/macro-economy/investment.yaml
While working on scenario-compass migration, I noticed that the electricity-investment variables were still missing.
=> Add investment variables for power generation, storage and grid

definitions/variable/emissions/emissions.yaml
Small fix of `Emissions|<gas>|Energy` incorrectly being described as CO2 emissions for all species.
=> fix species not flexible in energy emission descriptions

definitions/variable/macro-economy/income.yaml
I noticed this missing specification when validating ScenarioMIP submissions.
=> Skip region aggregate for income-share-by-decile variable

definitions/region/native_regions/REMIND-MAgPIE/REMIND-MAgPIE_3.2-4.6.yaml, definitions/region/native_regions/REMIND-MAgPIE/REMIND-MAgPIE_3.3-4.8.yaml, definitions/region/native_regions/REMIND-MAgPIE/REMIND_3.0.yaml, definitions/region/native_regions/REMIND-MAgPIE/REMIND_3.1.yaml, mappings/REMIND-MAgPIE/REMIND-MAgPIE_3.2-4.6.yaml, mappings/REMIND-MAgPIE/REMIND-MAgPIE_3.3-4.8.yaml, mappings/REMIND-MAgPIE/REMIND_3.0.yaml
For completeness and automated downscaling for the Scenario Compass project (@fabiosferra), this PR adds region-definitions and legacy mappings of the 12-region version of previous REMIND versions used in earlier projects.
=> Add region-definitions for legacy REMIND[-MAgPIE] versions

definitions/variable/afolu/agriculture.yaml
Crop yields can be based on physical or harvested area.
This PR refines the definition of the existing `Yield|Cropland|{Crop Types}` variables (physical) and adds new variables for yield based on harvested area `Yield|Cropland Harvested|{Crop Types}`.
=> More specific definition of crop yields

definitions/variable/sdg-indicators/sdg.yaml
Corrects a misspelling of `description` as `desciption` in two variables in `sdg-indicators/sdg.yaml`. Would close #318 .
=> Correct misspelled attribute in two SDG variables

definitions/region/native_regions/IMAGE_v3.3.yaml, definitions/region/native_regions/IMAGE_v3.4.yaml, mappings/IMAGE_v3.3.yaml
This PR copies over the addition of missing countries for IMAGE 3.4 as implemented by @jkikstra in #269 (but with cleaned-up formatting) and adds the same regions and mappings for IMAGE 3.3.
=> Region definition and mappings for IMAGE 3.3

mappings/COFFEE_1.5.yaml, mappings/GCAM_7.1.yaml, mappings/IMAGE_v3.4.yaml
South Korea was incorrectly categorized in a few models. I went through the list and fixed them.
=> Fix korea region

mappings/COFFEE/COFFEE_1.6.yaml
This PR applies the change in #257 (moving Korea to "China (R10)") for COFFEE 1.5 also to COFFEE 1.6.
Please confirm @lbbaptista!
FYI @jkikstra
=> Move R10 mapping of Korea to China

definitions/region/native_regions/REMIND-MAgPIE/REMIND-MAgPIE_3.2-4.6.yaml, definitions/region/native_regions/REMIND-MAgPIE/REMIND-MAgPIE_3.3-4.8.yaml, definitions/region/native_regions/REMIND-MAgPIE/REMIND-MAgPIE_3.4-4.8.yaml, definitions/region/native_regions/REMIND-MAgPIE/REMIND-MAgPIE_3.5-4.10.yaml, definitions/region/native_regions/REMIND-MAgPIE/REMIND_3.0.yaml, definitions/region/native_regions/REMIND-MAgPIE/REMIND_3.1.yaml
This PR applies the fix by @jkikstra in #266 - adding Kosovo to the native-region definitions - to the other native-region definitions of the REMIND model.
=> Add Kosovo to REMIND native-region definitions

definitions/variable/afolu/land-cover-change.yaml
The variable `Forest Area Change|Deforestation|Planted` was missing.
With this PR the 3 sub-categories 
Forest Area Change|Deforestation|Primary
Forest Area Change|Deforestation|Secondary
Forest Area Change|Deforestation|Planted
should add up to `Forest Area Change|Deforestation`
=> added missing variable `Forest Area Change|Deforestation|Planted`

definitions/variable/buildings/energy-services.yaml, definitions/variable/buildings/service.yaml, definitions/variable/buildings/stocks.yaml, definitions/variable/buildings/tag_appliances.yaml, definitions/variable/buildings/tag_heating_and_cooling_technologies.yaml, definitions/variable/buildings/tag_residential_building_type.yaml, definitions/variable/buildings/tag_residential_commercial.yaml, definitions/variable/buildings/tag_urban_rural.yaml, definitions/variable/buildings/tag_useful_vs_gross.yaml, definitions/variable/energy/tag_all_sectors.yaml
This PR adds further variables for the residential and commercial sectors. Thi includes:
- Stock of floorspace, and buidling types
- Renovation rates and building U-values
- Access to different appliance groups and heating or cooling technologies
- Some variables for "prosumers", including use of rooftop PV, prevalence of net-zero buildings
- Energy demand per different building energy services (cooling, heating, etc.)
Had to add a number of tags differentiating between
- Urban and rural households
- Residential building types
- Appliances groups
- heating and cooling technologies
=> Adding variable definitions for Residential and Commercial sectors

definitions/region/native_regions/GCAM/GCAM_7.0.yaml, definitions/region/native_regions/GCAM/GCAM_7.4.yaml
This PR adds Saint Helena to native-region-definition for GCAM versions added since #337 was started.
FYI @jkikstra
=> Add Saint Helena to new GCAM models
